pg = pg or {}
pg.child2_shop = {
	{
		goods_type = 1,
		name = "体能+10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2022,
		desc = "体能固定+10",
		goods_num = 1,
		resource_type = 1,
		id = 1,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知识+10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2023,
		desc = "知识固定+10",
		goods_num = 1,
		resource_type = 1,
		id = 2,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "实践+10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2024,
		desc = "实践固定+10",
		goods_num = 1,
		resource_type = 1,
		id = 3,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感知+10",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2025,
		desc = "感知固定+10",
		goods_num = 1,
		resource_type = 1,
		id = 4,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "心情+2",
		resource_num = 8,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2026,
		desc = "心情固定+2",
		goods_num = 1,
		resource_type = 1,
		id = 5,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体能+20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2027,
		desc = "体能固定+20",
		goods_num = 1,
		resource_type = 1,
		id = 6,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知识+20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2028,
		desc = "知识固定+20",
		goods_num = 1,
		resource_type = 1,
		id = 7,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "实践+20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2029,
		desc = "实践固定+20",
		goods_num = 1,
		resource_type = 1,
		id = 8,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感知+20",
		resource_num = 30,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2030,
		desc = "感知固定+20",
		goods_num = 1,
		resource_type = 1,
		id = 9,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "心情+4",
		resource_num = 12,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2031,
		desc = "心情固定+4",
		goods_num = 1,
		resource_type = 1,
		id = 10,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体能+40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2032,
		desc = "体能固定+40",
		goods_num = 1,
		resource_type = 1,
		id = 11,
		icon = "attr_tineng2"
	},
	{
		goods_type = 1,
		name = "知识+40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2033,
		desc = "知识固定+40",
		goods_num = 1,
		resource_type = 1,
		id = 12,
		icon = "attr_zhishi2"
	},
	{
		goods_type = 1,
		name = "实践+40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2034,
		desc = "实践固定+40",
		goods_num = 1,
		resource_type = 1,
		id = 13,
		icon = "attr_shijian2"
	},
	{
		goods_type = 1,
		name = "感知+40",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2035,
		desc = "感知固定+40",
		goods_num = 1,
		resource_type = 1,
		id = 14,
		icon = "attr_ganzhi2"
	},
	{
		goods_type = 1,
		name = "心情+6",
		resource_num = 15,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2036,
		desc = "心情固定+6",
		goods_num = 1,
		resource_type = 1,
		id = 15,
		icon = "res_xinqing2"
	},
	{
		goods_type = 1,
		name = "体能增益",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2001,
		desc = "（3回合）行程中获得体能增加",
		goods_num = 1,
		resource_type = 1,
		id = 16,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "知识增益",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2002,
		desc = "（3回合）行程中获得知识增加",
		goods_num = 1,
		resource_type = 1,
		id = 17,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "实践增益",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2003,
		desc = "（3回合）行程中获得实践增加",
		goods_num = 1,
		resource_type = 1,
		id = 18,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "感知增益",
		resource_num = 75,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2004,
		desc = "（3回合）行程中获得感知增加",
		goods_num = 1,
		resource_type = 1,
		id = 19,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "幸运奖券",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2005,
		desc = "「金钱」随机+20~100",
		goods_num = 1,
		resource_type = 1,
		id = 20,
		icon = "buff_2005"
	},
	{
		goods_type = 1,
		name = "体能随机增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2006,
		desc = "（3回合）行程总结时，随机获得少量体能",
		goods_num = 1,
		resource_type = 1,
		id = 21,
		icon = "benefit_2_tineng_1"
	},
	{
		goods_type = 1,
		name = "知识随机增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2007,
		desc = "（3回合）行程总结时，随机获得少量知识",
		goods_num = 1,
		resource_type = 1,
		id = 22,
		icon = "benefit_2_zhishi_1"
	},
	{
		goods_type = 1,
		name = "实践随机增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2008,
		desc = "（3回合）行程总结时，随机获得少量实践",
		goods_num = 1,
		resource_type = 1,
		id = 23,
		icon = "benefit_2_shijian_1"
	},
	{
		goods_type = 1,
		name = "感知随机增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2009,
		desc = "（3回合）行程总结时，随机获得少量感知",
		goods_num = 1,
		resource_type = 1,
		id = 24,
		icon = "benefit_2_ganzhi_1"
	},
	{
		goods_type = 1,
		name = "体能随机增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2010,
		desc = "（3回合）行程总结时，随机获得中量体能",
		goods_num = 1,
		resource_type = 1,
		id = 25,
		icon = "benefit_2_tineng_2"
	},
	{
		goods_type = 1,
		name = "知识随机增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2011,
		desc = "（3回合）行程总结时，随机获得中量知识",
		goods_num = 1,
		resource_type = 1,
		id = 26,
		icon = "benefit_2_zhishi_2"
	},
	{
		goods_type = 1,
		name = "实践随机增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2012,
		desc = "（3回合）行程总结时，随机获得中量实践",
		goods_num = 1,
		resource_type = 1,
		id = 27,
		icon = "benefit_2_shijian_2"
	},
	{
		goods_type = 1,
		name = "感知随机增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2013,
		desc = "（3回合）行程总结时，随机获得中量感知",
		goods_num = 1,
		resource_type = 1,
		id = 28,
		icon = "benefit_2_ganzhi_2"
	},
	{
		goods_type = 1,
		name = "体能随机·预增益",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2014,
		desc = "下回合结束时，随机获得大量体能",
		goods_num = 1,
		resource_type = 1,
		id = 29,
		icon = "benefit_2_tineng_3"
	},
	{
		goods_type = 1,
		name = "知识随机·预增益",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2015,
		desc = "下回合结束时，随机获得大量知识",
		goods_num = 1,
		resource_type = 1,
		id = 30,
		icon = "benefit_2_zhishi_3"
	},
	{
		goods_type = 1,
		name = "实践随机·预增益",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2016,
		desc = "下回合结束时，随机获得大量实践",
		goods_num = 1,
		resource_type = 1,
		id = 31,
		icon = "benefit_2_shijian_3"
	},
	{
		goods_type = 1,
		name = "感知随机·预增益",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2017,
		desc = "下回合结束时，随机获得大量感知",
		goods_num = 1,
		resource_type = 1,
		id = 32,
		icon = "benefit_2_ganzhi_3"
	},
	{
		goods_type = 1,
		name = "心情随机回复",
		resource_num = 25,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2018,
		desc = "（3回合）回合开始时，随机获得少量心情",
		goods_num = 1,
		resource_type = 1,
		id = 33,
		icon = "benefit_2_xinqing_1"
	},
	{
		goods_type = 1,
		name = "心情随机回复+",
		resource_num = 36,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2019,
		desc = "（3回合）回合开始时，随机获得中量心情",
		goods_num = 1,
		resource_type = 1,
		id = 34,
		icon = "benefit_2_xinqing_2"
	},
	{
		goods_type = 1,
		name = "心情随机回复++",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2020,
		desc = "（3回合）回合开始时，随机获得大量心情",
		goods_num = 1,
		resource_type = 1,
		id = 35,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 1,
		name = "心情随机回复(永久)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2021,
		desc = "回合开始时，随机获得心情",
		goods_num = 1,
		resource_type = 1,
		id = 36,
		icon = "benefit_2_xinqing_3"
	},
	{
		goods_type = 3,
		name = "行动力回复",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "购买后，行动力+1",
		goods_num = 1,
		resource_type = 1,
		id = 37,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 3,
		name = "行动力回复+",
		resource_num = 300,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 3,
		desc = "购买后，行动力+2",
		goods_num = 2,
		resource_type = 1,
		id = 38,
		icon = "res_xingdongli2"
	},
	{
		goods_type = 1,
		name = "体能转化·知识",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2037,
		desc = "（3回合）行程中获得体能增加，获得知识减少",
		goods_num = 1,
		resource_type = 1,
		id = 39,
		icon = "benefit_2_tinengzhishiz"
	},
	{
		goods_type = 1,
		name = "知识转化·体能",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2038,
		desc = "（3回合）行程中获得知识增加，获得体能减少",
		goods_num = 1,
		resource_type = 1,
		id = 40,
		icon = "benefit_2_zhishitinengz"
	},
	{
		goods_type = 1,
		name = "实践转化·感知",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2039,
		desc = "（3回合）行程中获得实践增加，获得感知减少",
		goods_num = 1,
		resource_type = 1,
		id = 41,
		icon = "benefit_2_shijianganzhiz"
	},
	{
		goods_type = 1,
		name = "感知转化·实践",
		resource_num = 150,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2040,
		desc = "（3回合）行程中获得感知增加，获得实践减少",
		goods_num = 1,
		resource_type = 1,
		id = 42,
		icon = "benefit_2_ganzhishijianz"
	},
	{
		goods_type = 1,
		name = "实践增益(切换)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2041,
		desc = "（效果循环切换）获得实践增加；获得实践减少",
		goods_num = 1,
		resource_type = 1,
		id = 43,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "实践增益(切换)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2043,
		desc = "（效果循环切换）获得实践增加；获得实践减少",
		goods_num = 1,
		resource_type = 1,
		id = 44,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "实践增益(切换)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2045,
		desc = "（效果循环切换）获得实践增加；获得实践减少",
		goods_num = 1,
		resource_type = 1,
		id = 45,
		icon = "benefit_2_shijianq_1"
	},
	{
		goods_type = 1,
		name = "体能增益(切换)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2047,
		desc = "（效果循环切换）获得体能增加；获得体能减少",
		goods_num = 1,
		resource_type = 1,
		id = 46,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "体能增益(切换)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2049,
		desc = "（效果循环切换）获得体能增加；获得体能减少",
		goods_num = 1,
		resource_type = 1,
		id = 47,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "体能增益(切换)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2051,
		desc = "（效果循环切换）获得体能增加；获得体能减少",
		goods_num = 1,
		resource_type = 1,
		id = 48,
		icon = "benefit_2_tinengq_1"
	},
	{
		goods_type = 1,
		name = "感知增益(切换)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2053,
		desc = "（效果循环切换）获得感知增加；获得感知减少",
		goods_num = 1,
		resource_type = 1,
		id = 49,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "感知增益(切换)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2055,
		desc = "（效果循环切换）获得感知增加；获得感知减少",
		goods_num = 1,
		resource_type = 1,
		id = 50,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "感知增益(切换)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2057,
		desc = "（效果循环切换）获得感知增加；获得感知减少",
		goods_num = 1,
		resource_type = 1,
		id = 51,
		icon = "benefit_2_ganzhiq_1"
	},
	{
		goods_type = 1,
		name = "知识增益(切换)",
		resource_num = 120,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2059,
		desc = "（效果循环切换）获得知识增加；获得知识减少",
		goods_num = 1,
		resource_type = 1,
		id = 52,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "知识增益(切换)+",
		resource_num = 240,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2061,
		desc = "（效果循环切换）获得知识增加；获得知识减少",
		goods_num = 1,
		resource_type = 1,
		id = 53,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "知识增益(切换)++",
		resource_num = 400,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2063,
		desc = "（效果循环切换）获得知识增加；获得知识减少",
		goods_num = 1,
		resource_type = 1,
		id = 54,
		icon = "benefit_2_zhishiq_1"
	},
	{
		goods_type = 1,
		name = "特殊行程格·一",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2089,
		desc = "第1个行程格获得属性少量增加",
		goods_num = 1,
		resource_type = 1,
		id = 55,
		icon = "benefit_2_xingcheng1_1"
	},
	{
		goods_type = 1,
		name = "特殊行程格·一+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2090,
		desc = "第1个行程格获得属性中量增加",
		goods_num = 1,
		resource_type = 1,
		id = 56,
		icon = "benefit_2_xingcheng1_2"
	},
	{
		goods_type = 1,
		name = "特殊行程格·一++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2091,
		desc = "第1个行程格获得属性大量增加",
		goods_num = 1,
		resource_type = 1,
		id = 57,
		icon = "benefit_2_xingcheng1_3"
	},
	{
		goods_type = 1,
		name = "奇数行程格增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2092,
		desc = "奇数行程格获得属性少量增加",
		goods_num = 1,
		resource_type = 1,
		id = 58,
		icon = "benefit_2_xingchengji_1"
	},
	{
		goods_type = 1,
		name = "奇数行程格增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2093,
		desc = "奇数行程格获得属性中量增加",
		goods_num = 1,
		resource_type = 1,
		id = 59,
		icon = "benefit_2_xingchengji_2"
	},
	{
		goods_type = 1,
		name = "奇数行程格增益++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2094,
		desc = "奇数行程格获得属性大量增加",
		goods_num = 1,
		resource_type = 1,
		id = 60,
		icon = "benefit_2_xingchengji_3"
	},
	{
		goods_type = 1,
		name = "偶数行程格增益",
		resource_num = 50,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2095,
		desc = "偶数行程格获得属性少量增加",
		goods_num = 1,
		resource_type = 1,
		id = 61,
		icon = "benefit_2_xingchengou_1"
	},
	{
		goods_type = 1,
		name = "偶数行程格增益+",
		resource_num = 180,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2096,
		desc = "偶数行程格获得属性中量增加",
		goods_num = 1,
		resource_type = 1,
		id = 62,
		icon = "benefit_2_xingchengou_2"
	},
	{
		goods_type = 1,
		name = "偶数行程格增益++",
		resource_num = 200,
		is_refresh = 1,
		limit_num = 1,
		goods_id = 2097,
		desc = "偶数行程格获得属性大量增加",
		goods_num = 1,
		resource_type = 1,
		id = 63,
		icon = "benefit_2_xingchengou_3"
	},
	all = {
		1,
		2,
		3,
		4,
		5,
		6,
		7,
		8,
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		42,
		43,
		44,
		45,
		46,
		47,
		48,
		49,
		50,
		51,
		52,
		53,
		54,
		55,
		56,
		57,
		58,
		59,
		60,
		61,
		62,
		63
	}
}
